instance_provision: 'spot_low_price'
region_name:
  - eu-west-1
user_credentials_path: '~/.ssh/scylla-qa-ec2'
instance_type_loader: 'c5.xlarge'
instance_type_monitor: 't3.large'
regions_data:
  us-east-1:
    security_group_ids: 'sg-c5e1f7a0'
    subnet_id: 'subnet-ec4a72c4'
    ami_id_loader: 'ami-00410516d864c4a80' # Loader dedicated AMI
    ami_id_monitor: 'ami-02eac2c0129f6376b' # Official CentOS Linux 7 x86_64 HVM EBS ENA 1901_01
  eu-west-1:
    security_group_ids: 'sg-059a7f66a947d4b5c'
    subnet_id: 'subnet-088fddaf520e4c7a8'
    ami_id_loader: 'ami-0a9a4dc9eb5fbf9e8' # Loader dedicated AMI
    ami_id_monitor: 'ami-0ff760d16d9497662' # Official CentOS Linux 7 x86_64 HVM EBS ENA 1901_01
  us-west-2:
    security_group_ids: 'sg-81703ae4'
    subnet_id: 'subnet-5207ee37'
    ami_id_loader: 'ami-0c6fe6ef0d47ae428' # Loader dedicated AMI
    ami_id_monitor: 'ami-01ed306a12b7d1c96' # Official CentOS Linux 7 x86_64 HVM EBS ENA 1901_01


aws_root_disk_size_monitor: 50  # GB, remove this field if default disk size should be used
aws_root_disk_size_db: 15
aws_root_disk_size_loader: 30  # GB, Increase loader disk in order to have extra space for a larger swap
aws_root_disk_name_monitor: "/dev/sda1"  # use "/dev/xvda" for Debian 8 image
ami_db_scylla_user: 'centos'
ami_loader_user: 'centos'
ami_monitor_user: 'centos'
