test_duration: 480

cs_duration: '0m'
cs_user_profiles:
    - test-cases/scale/templated-elasticity-tables.yaml

pre_create_schema: true
user_profile_table_count: 500
batch_size: 125

n_loaders: 5
n_monitor_nodes: 1
n_db_nodes: 3
add_node_cnt: 0

jmx_heap_memory: 1024 # this is a fix/workaround for https://github.com/scylladb/scylla/issues/7609

instance_type_db: 'i4i.xlarge'
instance_type_loader: 'c6i.4xlarge'
user_prefix: 'longevity-elasticity-many-small-tables'
root_disk_size_runner: 120


cluster_health_check: false

nemesis_class_name: 'NoOpMonkey'
nemesis_interval: 60

# TODO: remove when https://github.com/scylladb/scylla-tools-java/issues/175 resolved
stop_test_on_stress_failure: false
use_hdr_cs_histogram: true
