test_duration: 4320

cs_duration: '55m'
cs_user_profiles:
    - scylla-qa-internal/cust_d/templated_tables_mv.yaml

pre_create_schema: true

user_profile_table_count: 1000
batch_size: 20

n_loaders: 5
n_monitor_nodes: 1
n_db_nodes: 1
add_node_cnt: 5

jmx_heap_memory: 1024 # this is a fix/workaround for https://github.com/scylladb/scylla/issues/7609

instance_type_db: 'i3.8xlarge'
instance_type_loader: 'c5.4xlarge'
user_prefix: 'longevity-5000-tables'

# loader AMI with c-s ver. 4 and few fixes:
#  - fix NoSuchElementException
#  - enable control over both consistency levels: regular and serial
#  - bring shard awareness
regions_data:
  us-east-1:
    ami_id_loader: 'ami-0b94f0e897d884b1b'
  eu-west-1:
    ami_id_loader: 'ami-0bf19545bc7bc9e1f'
  us-west-2:
    ami_id_loader: 'ami-063a97bde47353690'

cluster_health_check: false

nemesis_class_name: 'ChaosMonkey'
nemesis_interval: 60


# TODO: enable back coredump on bad_alloc
# scylla/issues/4764 was blocking progress into the production issues we were trying to reproduce
# so we temporary removed the default `--abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc`
# once the issue would be solved we can enable it back.
append_scylla_args: '--blocked-reactor-notify-ms 500'

# TODO: remove when https://github.com/scylladb/scylla-tools-java/issues/175 resolved
stop_test_on_stress_failure: false
